# general_info.yaml
welcome_settings:
  commands: ['start', 'начать', 'привет', 'hello', 'старт']
  welcome_message: |
    Приветствую, {username}!

    Чтобы начать чат, напиши свой вопрос. Например:
    "Привет, бот! Я бы хотел, чтобы ты помог мне разобраться в структуре коллективного договора на предприятии."

    Или конкретный вопрос:
    "Сколько положений выделено в коллективном договоре на предприятии?"

chat_settings:
  default_username: "пользователь"
  error_message: "Произошла ошибка: {error}"