# telegram_info.yaml
welcome_settings:
  commands: ['start', 'начать', 'привет', 'hello', 'старт']
  welcome_message: |
    Приветствую, {username}!

    Чтобы начать чат, напиши свой вопрос. 
    
    В своем ответе я всегда буду исходить из фактов изложенных в внутренней документальной базе данных.
    
    Например:
    
    - "Привет, бот! Я бы хотел, чтобы ты помог мне разобраться в структуре коллективного договора на предприятии."

    Или конкретный вопрос.
    
    - "Какие меры контроля за выполнением коллективного договора предусмотрены?"
    
    p.s. 
    
    Если ты продолжишь свой диалог, то имей введу, что вся информация передаваемая через чат-бота обрабатывается и хранится в соответствие с №152-ФЗ РФ для улучшения и контроля качества работы персонального ассистента.
    
    С политикой по обработке персональных данных можно ознакомиться на сайте https://profkom-nevazot.ru/

chat_settings:
  default_username: "пользователь"
  error_message: "Произошла ошибка: {error}"